version: '3'
services:
  postgres:
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - "8080"
      - "5432"
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
      - "8080:8080"
    volumes:
      - data:/var/lib/postgresql/data

  nakama:
    build: .
    depends_on:
      - postgres
    environment:
      - URL_IMAGE_ACTOR=${URL_IMAGE_ACTOR}
      - URL_EXTERN_ACTORS=${URL_EXTERN_ACTORS}
      - METAFAB_GAME_ID=${METAFAB_GAME_ID}
      - METAFAB_GAME_PASS=${METAFAB_GAME_PASS}
      - METAFAB_GAME_WALLET_ID=${METAFAB_GAME_WALLET_ID}
      - METAFAB_GAME_FUNDING_ID=${METAFAB_GAME_FUNDING_ID}
      - METAFAB_GAME_SECRET_KEY=${METAFAB_GAME_SECRET_KEY}
      - METAFAB_GAME_PUBLISH_KEY=${METAFAB_GAME_PUBLISH_KEY}
      - METAFAB_CURRENCY_DUST=${METAFAB_CURRENCY_DUST}
      - METAFAB_COLLECTION_ACTORS=${METAFAB_COLLECTION_ACTORS}
      - METAFAB_COLLECTION_SECTORS=${METAFAB_COLLECTION_SECTORS}
      - METAFAB_COLLECTION_BOOSTERS=${METAFAB_COLLECTION_BOOSTERS}
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
        /nakama/nakama migrate up --database.address postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} &&
        exec /nakama/nakama --config /nakama/data/local.yml --database.address postgres:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB} --socket.server_key ${CLIENT_KEY}
    expose:
      - "7349"
      - "7350"
      - "7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
    links:
      - "postgres:db"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    restart: unless-stopped

volumes:
  data: